name: tasks_app
description: Task Management

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_app_name: ^0.1.1
  flutter_launcher_icons: ^0.11.0
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  multi_select_flutter: ^4.1.3
  horizontal_calendar: ^1.1.2
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.1

# App Name
flutter_app_name:
  name: 'Task Management'

# App Icon
flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/favicon.png'
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/Poppins.ttf